name: Python application test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd ./backend/itemService/createItem/
        pip3 install -r requirements.txt
        pip3 install pytest  # Ensure pytest is installed

    - name: Run pytest
      run: |
        cd ./backend/itemService/createItem/
        python3 -m pytest
