name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ca-central-1
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip3 install -r ./backend/itemService/createItem/requirements.txt -t ./backend/itemService/createItem/
          
      - name: Zip create item function
        run: |
          cd ./backend/itemService/createItem
          zip -r ../../../../infra/createItem.zip .
          cd -

      
      - name: Terraform Init and Apply
        run: |
          export TERRAFORM_CONFIG="${HOME}/.terraformrc"
          echo "credentials \"app.terraform.io\" { token = \"${{ secrets.TFE_TOKEN }}\" }" > ${TERRAFORM_CONFIG}
          terraform init
          terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        working-directory: ./infra
