name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List directory contents
        run: ls -la
      - name: change dir
        run: cd ..
      
      - name: List directory contents 2
        run: ls -la
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ca-central-1
      
      - name: Terraform Init and Apply
        run: |
          export TERRAFORM_CONFIG="${HOME}/.terraformrc"
          echo "credentials \"app.terraform.io\" { token = \"${{ secrets.TFE_TOKEN }}\" }" > ${TERRAFORM_CONFIG}
          terraform init
          terraform apply -auto-approve
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        working-directory: ./infra
